#!/bin/bash
set -eu

echo "WARNING: acmesh-patch-secret is deprecated, use acmesh-apply-secret instead."

ARG_DOMAIN="$1"
ARG_NAMESPACE="$2"
ARG_NAME="$3"

exec acmesh-apply-secret -domain "${ARG_DOMAIN}" -namespace "${ARG_NAMESPACE}" -name "${ARG_NAME}"
