#!/bin/bash
set -eu

ARG_DOMAIN="$1"
ARG_NAMESPACE="$2"
ARG_NAME="$3"

TLS_CRT_BASE64=$(cat "/data/${ARG_DOMAIN}/fullchain.cer" | base64 -w 0)
TLS_KEY_BASE64=$(cat "/data/${ARG_DOMAIN}/${ARG_DOMAIN}.key" | base64 -w 0)

exec kubectl patch -n "${ARG_NAMESPACE}" secret/"${ARG_NAME}" -p "{\"data\":{\"tls.crt\":\"${TLS_CRT_BASE64}\", \"tls.key\":\"${TLS_KEY_BASE64}\"}}"
